### ISSUE TITLE
Create Course leidt tot cursuskopie waarin UUID gelijk is

### ISSUE THREAD

**Issue by allardnaber** [rijksuniversiteit-groningen/b2-ExamManagement#8]
De Create Course knop maakt een kopie van een sjablooncursus of toets van vorig jaar. Het blijkt nu echter dat de UUID van deze nieuwe cursus gelijk is aan de oude cursus. Hierdoor zijn alle LTI-tools allemaal aan dezelfde cursus gekoppeld. Dit levert nu met name problemen op met Collaborate. 
Alle sessies die in een van de gekopieerde cursussen is gemaakt, verschijnen in alle gekopieerde cursussen én het sjabloon.

**Comment by jasper-smit** [comment]
Heb je een aantal voorbeelden?

**Comment by allardnaber** [comment]
`select pk1, course_id, UUID from course_main where UUID = ‘0dcc0c95c3d2483db5a9ef2fe50fd8c1’;`
397856 EXAM-WMIE14006-20200427 0dcc0c95c3d2483db5a9ef2fe50fd8c1
398007 EXAM-LQX026B05-20200504 0dcc0c95c3d2483db5a9ef2fe50fd8c1
397848 EXAM-EBE026A05-20200501 0dcc0c95c3d2483db5a9ef2fe50fd8c1
397888 EXAM-WMME19003-20200525 0dcc0c95c3d2483db5a9ef2fe50fd8c1
398084 EXAM-TEST-CIT-BP 0dcc0c95c3d2483db5a9ef2fe50fd8c1
397807 EXAM-WMFA19001-20200605 0dcc0c95c3d2483db5a9ef2fe50fd8c1
397201 ESI-TEMPLATE-ONLINE-ORAL-EXAM 0dcc0c95c3d2483db5a9ef2fe50fd8c1

**Comment by jasper-smit** [comment]
Gefixt
